field: 591b26a5-dab8-44d9-8fd0-04cf2f6b642e # Service Card
fieldLayouts:
  a8994448-1d2a-479a-8741-f4f6521df60f:
    tabs:
      -
        elements:
          -
            fieldUid: 38dbc41b-503c-45a2-8a47-202f185327c8 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53891821-078c-4101-b5f7-e2fa0f39c5af
            warning: null
            width: 100
          -
            fieldUid: d3fd6e28-aaa3-4ab0-a5e9-6dd1ddffc5ce # Service Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1b0c972-b2c9-4fb6-a2fe-7fc0182eb211
            warning: null
            width: 100
          -
            fieldUid: 875e1e02-90b0-4c7a-9278-6d4aaa1a5a86 # Service Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff3929d2-8421-4b90-a01e-ad11dbe43974
            warning: null
            width: 100
          -
            fieldUid: b10efdb1-25f2-4c44-bb1d-a01b0bf72945 # Service Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a35066b-41f1-47b9-ba1e-9e046d3d58c2
            warning: null
            width: 100
        name: Content
        uid: bc889b0a-be7f-4ef8-8aca-95b1a3509de3
fields:
  38dbc41b-503c-45a2-8a47-202f185327c8: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: null
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:4b938d7b-1055-4d7b-aad0-c5bc40947750' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:4b938d7b-1055-4d7b-aad0-c5bc40947750' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  875e1e02-90b0-4c7a-9278-6d4aaa1a5a86: # Service Description
    columnSuffix: ioqmzupe
    contentColumnType: text
    fieldGroup: null
    handle: serviceDesc
    instructions: null
    name: 'Service Description'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b10efdb1-25f2-4c44-bb1d-a01b0bf72945: # Service Link
    columnSuffix: usndsqtu
    contentColumnType: text
    fieldGroup: null
    handle: serviceLink
    instructions: null
    name: 'Service Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d3fd6e28-aaa3-4ab0-a5e9-6dd1ddffc5ce: # Service Header
    columnSuffix: tgxymbwr
    contentColumnType: text
    fieldGroup: null
    handle: serviceHeader
    instructions: null
    name: 'Service Header'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: serviceCard
name: 'Service Card'
sortOrder: 1
