fieldLayouts:
  160feb2e-f88b-44de-8504-fbb67226f3ee:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3ec9bf6d-c43e-4a58-a3b5-ad2f8abcf8e7
            warning: null
            width: 100
          -
            fieldUid: 1325cb30-d549-4ac7-b904-bcb8086b9b8f # Main Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16d49b71-57d3-4f58-a8ab-f522f7e1811f
            warning: null
            width: 100
          -
            fieldUid: 67dd4237-b6c2-4968-a0db-09c544257c2f # Post Content
            instructions: null
            label: 'About Content'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 186b26e2-6144-45be-af7c-cca39a68f1e3
            warning: null
            width: 100
          -
            fieldUid: 5dc12c22-ee64-469d-846e-5091ddc2e3b3 # Single Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6a2de6c-ae2c-48ec-bd1a-a8d3fab4170e
            warning: null
            width: 100
        name: Content
        uid: 84b40e0f-f95e-42ab-97c5-9ef23d2be797
handle: aboutPage
hasTitleField: false
name: 'About Page'
section: a892eb79-73bf-4774-af27-7b50a400543f # About Page
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
