fieldLayouts:
  81770796-090c-474a-a2bb-fb0b52742b76:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ddc929f9-c1f4-4ce0-86bd-b5a9b84406f9
            warning: null
            width: 100
          -
            fieldUid: 6a7656ff-a820-4b7b-ab00-2204f6a159bc # Author
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93efa3c6-c353-4e8c-9393-5ca1564aed0e
            warning: null
            width: 100
          -
            fieldUid: 8f9647af-f7e4-4f55-8788-f7b7cbc8fbda # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03731b38-aace-40fe-92f7-5b23d53ba3c9
            warning: null
            width: 100
          -
            fieldUid: 5dc12c22-ee64-469d-846e-5091ddc2e3b3 # Single Image
            instructions: 'Add image here for post'
            label: 'Post Image'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e083b31-b31b-486b-a441-c029d8d44193
            warning: null
            width: 100
          -
            fieldUid: 67dd4237-b6c2-4968-a0db-09c544257c2f # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90046db0-c7c0-49e6-8a45-9022ce5ee8b4
            warning: null
            width: 100
        name: Content
        uid: 6cbfbfa5-2776-4291-9675-896700b2fce1
handle: default
hasTitleField: true
name: Default
section: 57e4fbeb-d9f9-4628-a9e6-35b1301f1aa2 # Single Blog Post
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
