fieldLayouts:
  9a3133db-3450-47b8-937c-f75b2df237da:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b86f6ba4-8614-4fb9-af7e-8c4fc0b00dcc
            warning: null
            width: 100
          -
            fieldUid: 6a7656ff-a820-4b7b-ab00-2204f6a159bc # Author
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7221c711-b46e-4330-91f9-a45b7e188fba
            warning: null
            width: 100
          -
            fieldUid: 8f9647af-f7e4-4f55-8788-f7b7cbc8fbda # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1bb85fd-8675-4aef-ac1f-778d1cd4270c
            warning: null
            width: 100
          -
            fieldUid: 5dc12c22-ee64-469d-846e-5091ddc2e3b3 # Single Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e3ce3c2-21f1-4286-a541-6cf20a949680
            warning: null
            width: 100
          -
            fieldUid: 67dd4237-b6c2-4968-a0db-09c544257c2f # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00804cb2-ddb7-445d-9910-58f67ffc03ec
            warning: null
            width: 100
        name: Content
        uid: 517f028a-0bda-4f95-b0b8-057681ecd8e6
handle: default
hasTitleField: true
name: Default
section: df833317-d21f-4121-bd15-6ccef77529eb # Singe Portfolio Post
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
