fieldLayouts:
  81770796-090c-474a-a2bb-fb0b52742b76:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ddc929f9-c1f4-4ce0-86bd-b5a9b84406f9
            warning: null
            width: 100
        name: Content
        uid: 6cbfbfa5-2776-4291-9675-896700b2fce1
handle: default
hasTitleField: true
name: Default
section: 57e4fbeb-d9f9-4628-a9e6-35b1301f1aa2 # blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
