fieldLayouts:
  eb20d1af-ab61-4df4-b064-a47a4f0e7a54:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2694dcdb-92f1-4dfa-93c7-94b3f9a03388
            warning: null
            width: 100
          -
            fieldUid: 1325cb30-d549-4ac7-b904-bcb8086b9b8f # Main Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e3b2b99-3139-4dd3-9715-8422c2d34080
            warning: null
            width: 100
          -
            fieldUid: 5dc12c22-ee64-469d-846e-5091ddc2e3b3 # Single Image
            instructions: null
            label: 'Header Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b1be05a-0cda-4df2-8870-3e9e8f132590
            warning: null
            width: 100
          -
            fieldUid: e0903be7-2a36-4944-b933-2188eed07e1f # Location
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0231d21-3002-4d10-a0d2-722a0f956ca4
            warning: null
            width: 100
          -
            fieldUid: 0132417e-9134-4102-a506-270df04dd922 # Header Two
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e378c9aa-31ca-4307-821f-62b1309a1933
            warning: null
            width: 100
          -
            fieldUid: 8be015dd-90b6-4229-ba10-4826495e75cb # Company Logos Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12e34eca-027a-4aea-a2a2-53ab2fc5d0e5
            warning: null
            width: 100
          -
            fieldUid: 48074489-84bb-4624-be40-a8e552d3614e # Experience Card Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 620c9fcd-663a-45f2-ba05-d6fdc72f65fe
            warning: null
            width: 100
        name: Content
        uid: a09c6bb6-89d3-4662-b1f6-c9f59a0ecc7b
handle: homepage
hasTitleField: false
name: Homepage
section: ae19a794-7ae5-4f3c-8ea7-1516867ff974 # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
