fieldLayouts:
  29a80a39-5b01-4b6e-b930-9a6dde1cc090:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2c0cd865-4072-417f-b5be-44f08b7d082b
            warning: null
            width: 100
          -
            fieldUid: 591b26a5-dab8-44d9-8fd0-04cf2f6b642e # Service Card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2ad04a5-8c95-4993-85f5-bbc1daebf2b0
            warning: null
            width: 100
        name: Content
        uid: 1fce739f-bfee-4951-b707-656ce45be9ef
handle: servicesPage
hasTitleField: false
name: 'Services Page'
section: ef669da3-6247-4d55-8005-15e8fe01f0de # Services Page
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
