columnSuffix: vexxyllf
contentColumnType: text
fieldGroup: 7f8fd7db-5902-47b3-9a58-c47f26ad5cc9 # Page Headers
handle: headerThree
instructions: null
name: 'Header Three'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
