columnSuffix: cmnvwgsr
contentColumnType: text
fieldGroup: a992fd09-6bb3-493f-9e5b-e480e9ca07f1 # Common
handle: postAuthor
instructions: 'Author of the post'
name: Author
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
