dateModified: 1659850616
email:
  fromEmail: dylanbradramsey@gmail.com
  fromName: 'Dylan Ramsey'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/images/uploads/images'
    type: craft\fs\Local
    url: '@web/images/uploads/images'
meta:
  __names__:
    2e86db90-dacc-41d9-8b48-8507d5bcd4b6: 'Dylan Ramsey' # Dylan Ramsey
    4b938d7b-1055-4d7b-aad0-c5bc40947750: Images # Images
    5dc12c22-ee64-469d-846e-5091ddc2e3b3: 'Single Image' # Single Image
    6a7656ff-a820-4b7b-ab00-2204f6a159bc: Author # Author
    7f8fd7db-5902-47b3-9a58-c47f26ad5cc9: 'Page Headers' # Page Headers
    8be015dd-90b6-4229-ba10-4826495e75cb: 'Company Logos Matrix' # Company Logos Matrix
    8f9647af-f7e4-4f55-8788-f7b7cbc8fbda: Date # Date
    9b7ac66d-c8ff-477b-9546-2d00f7b17fb7: 'Services Page' # Services Page
    22a2fe98-21f0-4545-9064-34de25a66fec: 'Logo Image' # Logo Image
    38dbc41b-503c-45a2-8a47-202f185327c8: Icon # Icon
    57e4fbeb-d9f9-4628-a9e6-35b1301f1aa2: 'Single Blog Post' # Single Blog Post
    67dd4237-b6c2-4968-a0db-09c544257c2f: 'Post Content' # Post Content
    81ac7a5f-adcd-4761-a7cd-3e5ffd93c2d9: Homepage # Homepage
    591b26a5-dab8-44d9-8fd0-04cf2f6b642e: 'Service Card' # Service Card
    875e1e02-90b0-4c7a-9278-6d4aaa1a5a86: 'Service Description' # Service Description
    975da71e-a5f8-4e60-921b-3395a8a5e030: 'About Page' # About Page
    1325cb30-d549-4ac7-b904-bcb8086b9b8f: 'Main Header' # Main Header
    06179a13-0bb0-4edf-8b2c-4c659107d4f6: 'Blog Post List' # Blog Post List
    9556f1c2-777d-42c7-875e-3250a592baac: Navigation # Navigation
    0079526e-4159-4f6d-80b8-03c0075865d9: Navigation # Navigation
    0132417e-9134-4102-a506-270df04dd922: 'Header 2' # Header 2
    a77ee0fa-2c38-42e6-ade5-e78e19c914d6: 'Portfolio Post List' # Portfolio Post List
    a500f030-ccf3-49fc-bdc2-f04140624602: 'Company logos' # Company logos
    a574e5ad-1c70-43fe-8ca6-952d386c928a: 'Portfolio Post List' # Portfolio Post List
    a892eb79-73bf-4774-af27-7b50a400543f: 'About Page' # About Page
    a992fd09-6bb3-493f-9e5b-e480e9ca07f1: Common # Common
    ae19a794-7ae5-4f3c-8ea7-1516867ff974: Homepage # Homepage
    b10efdb1-25f2-4c44-bb1d-a01b0bf72945: 'Service Link' # Service Link
    c6993108-6aff-450f-b871-6779180db4f1: 'Service Card' # Service Card
    cf1d4cda-c224-41ff-b004-dcc79d68d2de: Default # Default
    d3fd6e28-aaa3-4ab0-a5e9-6dd1ddffc5ce: 'Service Header' # Service Header
    d53edcf4-a8b6-4b34-a0bd-4e29bfaaaa6e: 'Align Content' # Align Content
    d9514a15-5a29-4c90-8bb8-647e0ac191a4: 'Dylan Ramsey' # Dylan Ramsey
    df833317-d21f-4121-bd15-6ccef77529eb: 'Single Portfolio Post' # Single Portfolio Post
    e0903be7-2a36-4944-b933-2188eed07e1f: Location # Location
    ef2f3bae-c097-4b65-91d4-89e7dd90b462: 'Blog Post List' # Blog Post List
    ef669da3-6247-4d55-8005-15e8fe01f0de: 'Services Page' # Services Page
    fe5f7cce-9b68-451f-b132-e2dfb6de5e64: Default # Default
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  smith:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Dylan Ramsey'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
